web:
  image: nginx
  volumes:
    - ./templates:/etc/nginx/templates
    - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - ./html:/usr/share/nginx/html
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
